name: Meson Windows compile

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  CCACHE_DIR: "${{ github.workspace }}/.ccache"
  BASE_BRANCH: main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Setup Meson and Ninja
        run: pip3 install meson ninja
      
      - name: Prepare compiler cache
        id: prep-ccache
        shell: bash
        run: |
          mkdir -p "${CCACHE_DIR}"
          echo "::set-output name=dir::$CCACHE_DIR"
          echo "::set-output name=today::$(date -I)"
          
      - name: Load Cache
        id: windows-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.prep-ccache.outputs.dir }}
          key: ${{github.job}}-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.BASE_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.BASE_BRANCH}}
        continue-on-error: true
      
      - name: Setup Meson
        run: |
          meson setup builddir
      
      - name: Compilation
        run: |
          cd builddir
          meson compile --verbose
      
      # meson test does not work on Windows CI (I don't know why, so we need to register them here manually)
      - name: Run Tests
        shell: cmd
        run: |
          builddir\core\core_test.exe
          builddir\services\native_toolkit\ntk_test.exe 